### ISSUE TITLE
Missing /etc/kubernetes/admin.conf causes cluster provisioning to fail

### ISSUE THREAD

**Issue by mattock** [puppetlabs/kream#29]
## Describe the Bug

Bringing up the cluster fails because /etc/kubernetes/admin.conf is missing:

```
$ bundle exec rake cluster_up                                                                                                                              
Checking for local Vagrant images                                                                                                                                                   
Deploying Kuberntetes controller                                                                                                                                                    
(   ●  ) Deploying the Kubernetes controller...The SSH command responded with a non-zero exit status. Vagrant                                                                       
assumes that this means the command failed. The output for this command                                                                                                             
should be in the log above. Please read the output to determine what                                                                                                                
went wrong.                                                                                                                                                                         
(   ●  ) Deploying the Kubernetes controller... Kubernetes controller is ready                                                                                                      
Deploying worker nodes                                                                                                                                                              
You can check there progress with 'kubectl get nodes'                                                                                                                               
Checking if kubectl is installed                                                                                                                                                    
kubectl is installed                                                                                                                                                                
cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory                                                                                                             
Connection to 127.0.0.1 closed.                                                                                                                                                     
rake aborted!                                                                                                                                                                       
Net::SCP::Error: SCP did not finish successfully (1): scp: /home/vagrant/admin.conf: No such file or directory              
/home/samuli/opt/kream/vendor/bundle/ruby/2.7.0/gems/net-scp-3.0.0/lib/net/scp.rb:365:in `block (3 levels) in start_command'
/home/samuli/opt/kream/vendor/bundle/ruby/2.7.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:607:in `do_close'                 
/home/samuli/opt/kream/vendor/bundle/ruby/2.7.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:564:in `channel_closed'           
/home/samuli/opt/kream/vendor/bundle/ruby/2.7.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:675:in `channel_close'            
/home/samuli/opt/kream/vendor/bundle/ruby/2.7.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
```
At this point some of the machines have already been created:

```
$ vagrant status
Current machine states:

kube-master               running (virtualbox)
kube-replica-master-01    not created (virtualbox)
kube-replica-master-02    not created (virtualbox)
kube-node-01              running (virtualbox)
kube-node-02              running (virtualbox)
lb                        not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

The "vagrant up" process for kube-node-01 and kube-node-02 is still running in the background, which breaks things like "vagrant destroy kube-node-02":

```
$ ps aux|grep vagrant
samuli   2153460  0.0  0.0 216732  3312 pts/9    S    09:27   0:00 bash /usr/bin/vagrant up kube-node-01
samuli   2153461  0.0  0.0 216732  3252 pts/9    S    09:27   0:00 bash /usr/bin/vagrant up kube-node-02
samuli   2153463  0.0  0.0   3644  2044 pts/9    Sl   09:27   0:00 /opt/vagrant/bin/vagrant up kube-node-01
samuli   2153464  0.0  0.0   4700  2068 pts/9    Sl   09:27   0:00 /opt/vagrant/bin/vagrant up kube-node-02
samuli   2153472  6.3  0.6 785096 103000 pts/9   Sl   09:27   0:10 ruby /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant up kube-node-01
samuli   2153474  6.3  0.6 783872 100484 pts/9   Sl   09:27   0:10 ruby /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant up kube-node-02
samuli   2166078  0.0  0.0 216108   644 pts/7    S+   09:30   0:00 grep --color=auto vagrant
```
The only way to recover is to kill those "vagrant up" processes manually.

## Expected Behavior

The Kubernetes cluster should come up without errors. Or if admin.conf needs to crafted manually that should be documented somewhere.

## Steps to Reproduce

Apply PR https://github.com/puppetlabs/kream/issues/27 to fix the synced folders issue.

Then bring up the cluster from scratch with

```
bundle exec rake cluster_up
```

## Environment

```
$ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

$ vagrant --version
Vagrant 2.2.9
 
$ vboxmanage --version
6.1.16r140961
```

**Comment by henningxtro** [comment]
I ran into the same issue, but it is only the consequence of a non matching regex in _manifest/default.pp_.
Your kube-master.log should end with this Error:
`==> kube-master: Error: Could not find node statement with name 'default' or 'kube-master.mydomain.net' on node kube-master.mydomain.net`
VirtualBox passes the domain of the host via the DHCP Server of the internal Nat-Network, which can cause this.

You can fix this by changing the first line in _manifest/default.pp_ from
`node 'kube-master' {`
to
`node /^kube-master/ {`

**Comment by chelnak** [comment]
Closing as this no longer appears to be a problem.

Thanks for taking the time to open the issue.
